title: openSUSE Universe
title_short: Universe
description: Find out the websites within the openSUSE infrastructure
email: admin@opensuse.org
copyright: '© 2022 openSUSE contributors'
url: "https://universe.opensuse.org"
github_url: "https://github.com/openSUSE/universe-o-o"

plugins:
  - jekyll-locale

navbar_links:
  - locales

footer_links:
  -
    text: source_code
    link: https://github.com/openSUSE/universe-o-o
  -
    text: license
    link: https://github.com/openSUSE/universe-o-o/blob/master/COPYING

localization:
  mode       : auto
  locale     : en
  locales_set:
    ca:
      name: Català
    cs:
      name: Čeština
    da:
      name: Dansk
    de:
      name: Deutsch
    en:
      name: English
    es:
      name: Español
    et:
      name: Eesti
    fa:
      name: فارسی
    fi:
      name: Suomi
    hi:
      name: हिन्दी
    it:
      name: Italiano
    ja:
      name: 日本語
    mk:
      name: македонски
    pl:
      name: Polski
    pt_BR:
      name: Português
    pt_PT:
      name: Português europeu
    ru:
      name: Русский
    sv:
      name: Svenska
    zh_CN:
      name: 简体中文
    zh_TW:
      name: 繁體中文

theme: jekyll-theme-openSUSE

exclude: [README.md, Gemfile, Gemfile.lock, vendor]
